// Generated by CoffeeScript 1.9.0
var draw, setup, x;

x = 0;

setup = function() {
  console.log("Setup Stage!");
  return createCanvas(800, 600).parent("main-page");
};

draw = function() {
  console.log("Draw Stage!");
  fill(0);
  ellipse(x, 100, 80, 80);
  return x = x >= 800 ? 0 : x + 10;
};
