// Generated by CoffeeScript 1.9.0
var draw, setup;

setup = function() {
  console.log("Setup Stage!");
  return createCanvas(800, 600).parent("main-page");
};

draw = function() {
  console.log("Draw Stage!");
  return ellipse(50, 50, 80, 80);
};
