// Generated by CoffeeScript 1.9.0
var draw, drawSegment, segLength, segment, setup, x, y;

x = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];

y = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];

segLength = 18;

setup = function() {
  createCanvas(640, 360);
  strokeWeight(9);
  return stroke(255, 100);
};

draw = function() {
  var i, _results;
  background(0);
  drawSegment(0, mouseX, mouseY);
  i = 0;
  _results = [];
  while (i < x.length - 1) {
    drawSegment(i + 1, x[i], y[i]);
    _results.push(i++);
  }
  return _results;
};

drawSegment = function(i, xin, yin) {
  var angle, dx, dy;
  dx = xin - x[i];
  dy = yin - y[i];
  angle = atan2(dy, dx);
  x[i] = xin - cos(angle) * segLength;
  y[i] = yin - sin(angle) * segLength;
  return segment(x[i], y[i], angle);
};

segment = function(x, y, a) {
  push();
  translate(x, y);
  rotate(a);
  line(0, 0, segLength, 0);
  return pop();
};
