// Generated by CoffeeScript 1.9.0
var draw, setup;

setup = function() {
  return console.log("Setup Stage!");
};

draw = function() {
  console.log("Draw Stage!");
  return ellipse(50, 50, 80, 80);
};
