// Generated by CoffeeScript 1.9.0
var draw, setup;

setup = function() {
  createCanvas(640, 360).parent("main-page");
  stroke(255);
  return noFill();
};

draw = function() {
  var i, _results;
  background(0);
  i = 0;
  _results = [];
  while (i < 200) {
    bezier(mouseX - (i / 2.0), 40 + i, 410, 20, 440, 300, 240 - (i / 16.0), 300 + (i / 8.0));
    _results.push(i += 20);
  }
  return _results;
};
