// Generated by CoffeeScript 1.9.0
var draw, i, setup;

i = 0;

setup = function() {
  alert("Setup Stage");
  return console.log("Setup Stage!");
};

draw = function() {
  if (i === 0) {
    alert("Draw Stage! It will repeat~ check `console.log` out");
  }
  i++;
  return console.log("Draw Stage!");
};
